export const content = {
  notFount: 'Ничего не найдено',
  open: 'Открыть',
  close: 'Закрыть',
  noTenants: 'Жильцов пока нет',
  address: 'Адресс',
  street: 'Улица',
  house: 'Дом',
  flat: 'Квартира/Офис',
  enterAddress: 'Укажите адресс, и здесь отобразится список жильцов',
  addTenantProfile: 'Добавить профиль жильца',
  editTenantProfile: 'Редактировать профиль жильца',
  cancel: 'Отмена',
  add: 'Добавить',
  edit: 'Редактировать',
  delete: 'Удалить',
  fullName: 'Ф.И.О',
  phoneNumber: 'Номер телефона',
  email: 'Email',
  requiredField: 'Поле обязательно для заполнения',
  addTenant: 'Добавить жильца',
  editProfile: 'Редактировать профиль',
  invalidEmail: 'Введите корректный адрес'
}